# Задание №1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [2]:
a =int(input('Введите число: '))
x=np.arange(a)

Введите число: 7


In [4]:
np.flip(x, 0)

array([6, 5, 4, 3, 2, 1, 0])

# Задание №2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [5]:
a =int(input('Введите число: '))
x=np.arange(a)

Введите число: 5


In [6]:
np.diag(np.flip(x, 0))

array([[4, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0]])

# Задание №3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [7]:
M = np.array([[4,2,1], [1,3,0], [0,5,4]])
v = np.array([4, 12, -3])

In [8]:
from numpy import linalg

In [9]:
linalg.solve(M, v)

array([ 0.46666667,  3.84444444, -5.55555556])

# Задание №4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [10]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

#### На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [11]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

#### Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [12]:
import matplotlib.pyplot as plt

In [13]:
def angle(v1, v2):
    # длины векторов
    v1Length = np.linalg.norm( v1 )
    v2Length = np.linalg.norm( v2 )
    cos_v1v2 = np.dot( v1,v2 ) /  ( v1Length * v2Length )
    return np.arccos( cos_v1v2 ) * 360 / 2 / np.pi

In [14]:
temp_ag = 180 # ставлю для сравнения самый большой угол
for i in users_stats:
    ag = angle(i, next_user_stats)
    if ag < temp_ag:
        temp_ag = ag
        similar_user = i
print (similar_user )

[0 1 1 0 0 0]
